### ISSUE TITLE
New design for homepage

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#101]
Another medium-sized design project. @tinnei and Cathy (what's your GitHub username?) have raised hands to take a first crack at this, but contributions and feedback are very, very welcome.

The problem: as a user landing on the site, it's hard to tell what's going on. 400+ projects are a lot to digest and makes it hard to for me to build trust in the site. 

Solution: create a curatable homepage that emphasizes the most important or needy projects, and the information both volunteers and projects owners need to get the help they need. And add images to help make everything more digestible.

Tentative tagline? `Helping projects get the resources they need.`

Design inspiration:
* https://www.catchafire.org/ 
* https://kickstarter.com
* What else?

Current site traffic is 50/50 but design for mobile first.

**Comment by caseypugh** [comment]
We have a [final-ish design](https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=188%3A2224) for new homepage. 
![image](https://user-images.githubusercontent.com/156097/78278624-4eb3e780-74e4-11ea-8e72-611c782b49bb.png)

More changes are coming but will probably be minor. [Figma link](https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=188%3A2224) also has mobile version. 

This is enough for us to start building out the core components:
- [ ] Top level splash area with headline/tagline
- [ ] Build project "card" component that will be reused throughout homepage and eventually project listing/index
- [ ] Make the navigation bar "sticky". Meaning, as you scroll down the page, it should stick to the top of the window.
- [ ] Display a row of top featured projects. For now this can be first 3 pinned projects. This will probably change later.
- [ ] Same as above, but display row of pinned projects by category
- [ ] We have a new set of "top-level" categories that group the existing categories together. [See here for our draft](https://docs.google.com/spreadsheets/d/1p6oR087N8dUJj3pTmt0zqpg54nCSnbv2Nxp8pgTBq28/edit#gid=1203571287)
- [ ] Display list events. I imagine this might be hardcoded for now or perhaps can be pulled from a public Google calendar.

**Comment by adrianthedev** [comment]
I picked this up. I will have a PR soon.

**Comment by cat-liu** [comment]
Hi all, here is the finished ver. of the both the desktop and mobile versions of the homepage. Adrian, @tinnei added the assets on the side, let us know if you need anything else. 

Head over to the [https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=392%3A0](url) for v.6 final version.

![image](https://user-images.githubusercontent.com/20099770/78461775-be5ed980-7680-11ea-8044-47ad5191f564.png)

**Comment by tinnei** [comment]
^Fyi, the finished version is similar to the final-ish one posted last week. The differences are:
- added search bar on header
- added mobile version
- pulled out graphics and icons on the right

Also added default image to assets:
<img width="245" alt="Screen Shot 2020-04-04 at 3 42 45 PM" src="https://user-images.githubusercontent.com/9310999/78462875-55c92a00-768b-11ea-8d94-efb375c5f8ed.png">

**Comment by cat-liu** [comment]
UPD 4/4 from @tinnei and I. Passing off onto dev, let us know if you have any questions.

Final Homepage link via Figma: [https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=408%3A2132](url)

A few quick changes today before finalizing:

**Increased the image size on project card so that it is bigger. Now it is 367x130**
![image](https://user-images.githubusercontent.com/20099770/78463955-3a185080-7698-11ea-88dc-d8036d7608c2.png)

**Finished mobile version of desktop** 
![image](https://user-images.githubusercontent.com/20099770/78463964-6764fe80-7698-11ea-9329-6d369cbd83f2.png)

**Added assets section** 
![image](https://user-images.githubusercontent.com/20099770/78463972-806daf80-7698-11ea-933e-c079f3a44378.png)

**Default images for each parent category**
![image](https://user-images.githubusercontent.com/20099770/78463979-a1360500-7698-11ea-8b95-2058df884f28.png)

**Default version of Homepage and Mobile on Figma**
![image](https://user-images.githubusercontent.com/20099770/78463988-b743c580-7698-11ea-8a6e-b9401299b9d9.png)

**Comment by caseypugh** [comment]
@tinnei @cat-liu as we're building this out, thinking through some of the top-level information on project cards. Showing the date of when something was created for every project might not be too relevant. Knowing that a project is 30 days old vs 1 day old doesnt mean too much to me. Thoughts on just removing it?

**Comment by cat-liu** [comment]
@caseypugh I thought it would be useful information in terms of sorting, explaining the progress of a project in comparison to the number of days since it has started/in progress/launched and would be good for volunteers to decide whether they want to join a project that is more established or more early stage.
