### ISSUE TITLE
Find Projects Page - Volunteers needed

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#222]
When sorting by volunteers needed, shows projects that are not looking for volunteers:

![image](https://user-images.githubusercontent.com/2389662/81040511-81e9ed80-8e79-11ea-83d3-a4d2c5e0cd2b.png)

https://helpwithcovid.com/projects/222-spira-s-sms-covid-19-tracker

![image](https://user-images.githubusercontent.com/2389662/81040542-95955400-8e79-11ea-821d-3fb94343758c.png)

**Comment by shen-sat** [comment]
I can take this one @prophesy604 🙌  I'm signing off now, will start work on it tomorrow

**Comment by shen-sat** [comment]
Hey @prophesy604. Looking at the code, this is expected behaviour: When you click 'Volunteers Needed' in the 'Sort by' section, the page loads all the projects sorted by the number of volunteers each project has (ie projects with fewest/0 volunteers will appear towards the top).

I'm guessing we should keep this functionality for users who want to search for projects who need the most help (ie have fewer volunteers).

I'm also assuming what you need as an admin is a filter ie an extra option in the 'Filter by' section to filter in/out projects that have no volunteers. If I'm correct, shall we make this a feature that only admins can use?

**Comment by prophesy604** [comment]
It should check if the project has closed volunteers aka volunteers filled. if it has, it should not show those projects when you sort by volunteers needed cause they do not need volunteers. in addition to the existing behaviour of showing fewest/0...

does that make sense? @shen-sat

**Comment by prophesy604** [comment]
I just verified that the project details page looks at the person's skillset and shows whether the project is accepting volunteers.

My profile did not have the funding skillset, now that I've added it - the project details page allows me to volunteer:

![image](https://user-images.githubusercontent.com/2389662/81173863-ba1f2800-8f6e-11ea-877c-8007d3fc8d61.png)

So since the find projects page sort by "volunteers needed" is using the expected behaviour based on the count.  i don't believe it should go by the skills indicated in the profile on this page. closing ticket.
