### ISSUE TITLE
Add ability to sort projects and volunteers

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#56]
**For projects:**
- "Sort by newest"
- Sort by ASC/DESC
- (maybe) Sort by number of volunteers needed?

**For volunteers:**
- "Sort by newest"
- Sort by ASC/DESC

**Comment by tiegz** [comment]
Assuming the goal of "number of volunteers" needed is to surface projects that are more in-need:

WDYT about a "remaining number of volunteers needed"? e.g. "# of volunteers needed - # of volunteers". 

i.e. if a project needs 50 volunteers and has 100 volunteers, shouldn't it surface lower because it's met its demand?

**Comment by sradu** [comment]
I believe this is up. We should create a new issue if we want to tweak it.
