### ISSUE TITLE
More visual cues to categories

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#65]
Suggested category color separation, definitely up to revision!

### Color 1
- Track the outbreak
- Reduce spread
- News and information

### Color 2
- Scale testing
- Medical facilities
- Medical equipments
- Treatment R&D

### Color 3
- Help out communities
- Map volunteers to needs
- E-Learning
- Job placement
- Mental health
- Social giving

### Color 4
- Other

**Comment by shen-sat** [comment]
Hi, I'm a junior ruby/rails dev and I'd like to help out by fixing this issue :)

Just to confirm my understanding of the issue: some of the projects are already color coded - the top ones appear orange-y whilst the rest are white (though I'm not sure what this color coding is for..?). Are you looking to extend this same type of coloring to the rest of the projects using other colors?

**Comment by caseypugh** [comment]
hi @shen-sat - I believe what we need is to create unique colors for each of the categories listed here. https://helpwithcovid.com/  
![image](https://user-images.githubusercontent.com/156097/77941616-71e25b00-7288-11ea-8d3b-b2e8979a5b03.png)

I think we'd simply hardcode these colors in the code. Perhaps creating a unique CSS class for each group of categories?

@tinnei - what's the reasoning behind grouping them together? Is it because they have a theme that connect them?

**Comment by caseypugh** [comment]
@tinnei @cat-liu just wondering if this is something you still want now that the homepage is live. Would be helpful to spec the task out more if so (e.g. what are colors 1/2/3?)

**Comment by colin-johnston** [comment]
@tinnei @caseypugh I would argue that the color-coding might not scale well across the category page designs, but I'd like to quickly create some mocks that see if it works without becoming too visually noisy. I've started cleaning up the WIP colors for labels, synching them up with the category-specific project placeholder images. I should have something or us to look at tomorrow.

**Comment by shen-sat** [comment]
Hey all, sorry for the radio silence - I'm still able to work on this :) I guess once we have the mocks to look at (ie once I know what colors to implement), I will begin work 👍

**Comment by caseypugh** [comment]
no longer relevant
